TKQClock/Controllers/ClockStoreController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TKQClock.Models;
using PagedList;
using PagedList.Mvc;

namespace TKQClock.Controllers
{
    public class ClockStoreController : Controller
    {
        // GET: ClockStore
        TKQClockDataContext data = new TKQClockDataContext();
        private List<DongHo> layDongho(int count)
        {
            return data.DongHos.OrderByDescending(a => a.NgayCapNhat).Take(count).ToList();
        }

        public ActionResult IndexBefore(int? page)
        {
            var newclock = layDongho(1000);
            int pagesize = 9;
            int pageNum = (page ?? 1);
            return View(newclock.ToPagedList(pageNum, pagesize));
        }
        public ActionResult Index(int? page )
        {
            var newclock = layDongho(15);
            int pagesize = 9;
            int pageNum = (page ?? 1);
            return View(newclock.ToPagedList(pageNum, pagesize));
        }

        public ActionResult Hang()
        {
            var hangs = from hang in data.HangDongHos select hang;
            return PartialView(hangs);
        }

        public ActionResult Loai()
        {
            var loais = from loai in data.LoaiDongHos select loai;
            return PartialView(loais);
        }
        public ActionResult ClockTheoHang(int id)
        {
            var clocks = from clock in data.DongHos where clock.MaHDH == id select clock;
            return View(clocks);
        }
        public ActionResult ClockTheoLoai(int id)
        {
            var clocks = from clock in data.DongHos where clock.MaLoai == id select clock;
            return View(clocks);
        }

        public ActionResult Chitietdongho(int id)
        {
            var clocks = from clock in data.DongHos
                       where clock.MaDH == id
                       select clock;
            return View(clocks.Single());
        }
    }
}

TKQClock/Controllers/TinTucController.cs
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TKQClock.Models;

namespace TKQClock.Controllers
{
    public class TinTucController : Controller
    {
        // GET: TinTuc
        TKQClockDataContext data = new TKQClockDataContext();
        private List<TinTuc> layTintuc(int count)
        {
            return data.TinTucs.OrderByDescending(a => a.NgayTao).Take(count).ToList();
        }
        public ActionResult Index(int? page)
        {
            var items = layTintuc(100);
            int pagesize = 3;
            int pageNum = (page ?? 1);
            return View(items.ToPagedList(pageNum, pagesize));
        }
        public ActionResult TinTuc()
        {
            var items = data.TinTucs.ToList();
            return View(items);
        }
        public ActionResult NoiDungTinTuc(int id)
        {

            var tts = from tt in data.TinTucs
                      where tt.MaTT == id
                      select tt;
            return View(tts.Single());
        }
        public ActionResult Partial_New()
        {
            var items = data.TinTucs.Take(3).ToList();
            return View(items);
        }
    }
}

TKQClock/Views/Shared/_LayoutAdmin.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/Content/admin.css" rel="stylesheet" />
    <link href="~/Content/ClockStoreCss/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/ClockStoreCss/shop-homepage.css" rel="stylesheet" />
    <link rel="shortcut icon" href="~/images/LOGO1.png" type="image/x-icon" />
</head>
<body style="padding-top: 0px">
    <style>
        center {
            display: none;
        }
    </style>
    <div id="nav-admin" style="z-index: 10 !important;">
        <div class="nav-admin-section">
            <ul id="admin-section">
                <li> @Html.ActionLink("Tài khoản", "Dangnhap", "admin")</li>
            </ul>
        </div>
    </div>
    <div class="container" style="padding-top:55px">
        @RenderBody()
    </div>

</body>
</html>

TKQClock/Views/Shared/_LayoutPage.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <link rel="stylesheet" href="~/Content/ClockStoreCss/detail.css">
    <link rel="stylesheet" href="~/Content/ClockStoreCss/style.css">
    <link rel="stylesheet" href="~/Content/ClockStoreCss/ThemeCart.css">
    <link rel="stylesheet" href="~/Content/ClockStoreCss/responsive.css">
    @*    <link href="~/Content/ClockStoreCss/bootstrap.min.css" rel="stylesheet" />
        <link href="~/Content/ClockStoreCss/shop-homepage.css" rel="stylesheet" />*@
    <link rel="stylesheet" href="~/Content/themify-icons/themify-icons.css">
    <link rel="shortcut icon" href="~/images/LOGO1.png" type="image/x-icon" />

</head>
<body>
    <style>
        center {
            display: none;
        }
    </style>
    <div class="main" style="z-index: 10 !important;">
        <div id="header">
            <ul id="nav">
                <li>
                    @Html.ActionLink("HOME", "Index", "ClockStore")
                </li>
                <li>
                    <a href="#">Hãng </a>
                    <ul class="subnav">
                        @Html.Action("Hang", "ClockStore")
                    </ul>
                </li>
                <li>
                    <a href="#">Loại</a>
                    <ul class="subnav">
                        @Html.Action("Loai", "ClockStore")
                    </ul>
                </li>
                <li><a href="https://goo.gl/maps/Gx1em5MJjvHZjdwq7">Địa chỉ<i class="icon-cont ti-location-pin"></i></a></li>
                <li>
                    @*<a href="#">Giỏ hàng <i class="icon-shopping ti-shopping-cart"></i></a>*@
                    @Html.Action("GiohangPartial", "Giohang")

                <li>
                    @*<a href="#">Tài khoản <i class="icon-user ti-user"></i></a>*@
                    @Html.ActionLink("Tài khoản", "Dangnhap", "User")
                </li>
                </li>
                <li><a href="#contact">Hỗ trợ <i class="icon-help ti-headphone-alt"></i></a></li>
            </ul>
            <div id="mobile-menu" class="mobile-menu-btn">
                <i class="menu-icon ti-menu"></i>
            </div>
            <!-- begin search button -->
        </div>

        <div>
            @RenderBody()
        </div>

        @*
            <div id="footer">
                <div class="social-list">
                    <a href=""><i class="ti-facebook"></i></a>
                    <a href=""><i class="ti-instagram"></i></a>
                    <a href=""><i class="ti-youtube"></i></a>
                    <a href=""><i class="ti-pinterest"></i></a>
                    <a href=""><i class="ti-twitter"></i></a>
                    <a href=""><i class="ti-linkedin"></i></a>
                </div>
                <p class="copyright">Copyright © 2023  TKQ Team. All rights reserved.</p>
            </div>*@
    </div>

</body>
</html>

TKQClock/Views/Shared/_LayoutQL.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/Content/demo1.css" rel="stylesheet" />
    <link href="~/Content/admin.css" rel="stylesheet" />
    <link href="~/Content/ClockStoreCss/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/ClockStoreCss/shop-homepage.css" rel="stylesheet" />
    <link rel="shortcut icon" href="~/images/LOGO1.png" type="image/x-icon" />
    <script src="~/tinymce/js/tinymce/tinymce.min.js"></script>
    <script>tinymce.init({ selector: 'textarea' });</script>
</head>
<body style="padding-top: 0px; z-index: 10 !important; " >
    <style>
        center {
            display: none;
        }
    </style>
    <div id="nav-admin">
        <div class="nav-admin-section">
            <ul id="admin-section">
                <li>@Html.ActionLink("Đồng Hồ", "Dongho", "admin")</li>
                <li>@Html.ActionLink("Tin Tức ", "TinTuc", "admin")</li>
                <li>@Html.ActionLink("Đơn Đặt Hàng", "DonDatHang", "admin")</li>
                <li>@Html.ActionLink("Hãng Đồng Hồ", "HangDH", "admin")</li>
                <li>@Html.ActionLink("Loại Đồng Hồ", "TheLoaiDH", "admin")</li>
                <li>@Html.ActionLink("Khách Hàng", "Khachhang", "admin")</li>
            </ul>
        </div>
    </div>
    <div class="container" style="padding-top:55px">
        @RenderBody()
    </div>
</body>
</html>

TKQClock/Views/Shared/_LayoutRegister.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <link rel="stylesheet" href="~/Content/ClockStoreCss/signup.css">
    <link rel="stylesheet" href="~/Content/ClockStoreCss/responsive.css">
    <link rel="shortcut icon" href="~/images/LOGO1.png" type="image/x-icon" />
    <link rel="stylesheet" href="~/Content/themify-icons/themify-icons.css">
</head>
<body>
    <style>
        center {
            display: none;
        }
    </style>
    <div id="header" style="z-index: 10 !important;">
        <ul id="nav">
            <li>@Html.ActionLink("Trang Chủ", "Index", "ClockStore")</li>
            <li>
                <a href="#footer">Hỗ Trợ</a>
            </li>
        </ul>
        <div id="mobile-menu" class="mobile-menu-btn">
            <i class="menu-icon ti-menu"></i>
        </div>
        <!-- begin search button -->
    </div>
    <div>
        @RenderBody()
    </div>
    <div id="footer">
        <div class="social-list">
            <a href=""><i class="ti-facebook"></i></a>
            <a href=""><i class="ti-instagram"></i></a>
            <a href=""><i class="ti-youtube"></i></a>
            <a href=""><i class="ti-pinterest"></i></a>
            <a href=""><i class="ti-twitter"></i></a>
            <a href=""><i class="ti-linkedin"></i></a>
        </div>
        <p class="copyright">Copyright © 2023  TKQ Team. All rights reserved.</p>
    </div>
</body>
</html>

TKQClock/Views/Shared/_LayoutShoppingCart.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <link rel="stylesheet" href="~/Content/ClockStoreCss/style.css">
    <link rel="stylesheet" href="~/Content/ClockStoreCss/detail.css">
    <link rel="stylesheet" href="~/Content/ClockStoreCss/responsive.css">
    <link rel="stylesheet" href="~/Content/ClockStoreCss/ThemeCart.css">
    @*    <link rel="stylesheet" href="~/Content/ClockStoreCss/giohang.css">*@
    @*    <link href="~/Content/ClockStoreCss/bootstrap.min.css" rel="stylesheet" />
        <link href="~/Content/ClockStoreCss/shop-homepage.css" rel="stylesheet" />*@
    <link rel="stylesheet" href="~/Content/themify-icons/themify-icons.css">
    <link rel="shortcut icon" href="~/images/LOGO1.png" type="image/x-icon" />

</head>
<body>
    <style>
        center {
            display: none;
        }
    </style>
    <div class="main">
        <div id="header" style="z-index: 10 !important;">
            <ul id="nav">
                <li>
                    @Html.ActionLink("HOME", "Index", "ClockStore")
                </li>
                <li>
                    <a href="#">Hãng </a>
                    <ul class="subnav">
                        @Html.Action("Hang", "ClockStore")
                    </ul>
                </li>
                <li>
                    <a href="#">Loại</a>
                    <ul class="subnav">
                        @Html.Action("Loai", "ClockStore")
                    </ul>
                </li>
                <li><a href="https://goo.gl/maps/Gx1em5MJjvHZjdwq7">Địa chỉ<i class="icon-cont ti-location-pin"></i></a></li>
                <li>
                    @*<a href="#">Giỏ hàng <i class="icon-shopping ti-shopping-cart"></i></a>*@
                    @Html.Action("GiohangPartial", "Giohang")

                <li>
                    @*<a href="#">Tài khoản <i class="icon-user ti-user"></i></a>*@
                    @Html.ActionLink("Tài khoản", "Dangnhap", "User")
                    <ul class="subnav">
                        @Html.ActionLink("Đăng xuất", "Dangxuat", "User")
                    </ul>
                </li>
                </li>
                <li><a href="#contact">Hỗ trợ <i class="icon-help ti-headphone-alt"></i></a></li>
            </ul>
            <div id="mobile-menu" class="mobile-menu-btn">
                <i class="menu-icon ti-menu"></i>
            </div>
            <!-- begin search button -->
        </div>

        <div>
            @RenderBody()
        </div>

        @*        <div id="footer">
                <div class="social-list">
                    <a href=""><i class="ti-facebook"></i></a>
                    <a href=""><i class="ti-instagram"></i></a>
                    <a href=""><i class="ti-youtube"></i></a>
                    <a href=""><i class="ti-pinterest"></i></a>
                    <a href=""><i class="ti-twitter"></i></a>
                    <a href=""><i class="ti-linkedin"></i></a>
                </div>
                <p class="copyright">Copyright © 2023  TKQ Team. All rights reserved.</p>
            </div>*@
    </div>

</body>
</html>

TKQClock/Views/Shared/_LayoutTinTuc.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <link rel="stylesheet" href="~/Content/ClockStoreCss/detail.css">
    <link href="~/Content/fondendfix.css" rel="stylesheet" />
    @*    <link rel="stylesheet" href="~/Content/ClockStoreCss/ThemeCart.css">*@
    @*@<link rel="stylesheet" href="~/Content/ClockStoreCss/responsive.css">*@
    <link href="~/Content/ClockStoreCss/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/ClockStoreCss/shop-homepage.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/Content/themify-icons/themify-icons.css">
    <link rel="stylesheet" href="~/Content/ClockStoreCss/tintuc.css" />
    <link href="~/Content/admin.css" rel="stylesheet" />
    <link href="~/Content/demo1.css" rel="stylesheet" />
    <link rel="shortcut icon" href="~/images/LOGO1.png" type="image/x-icon" />

</head>
<body>
    <style>
        center {
            display: none;
        }
    </style>
    <div class="main">
        <div id="header" style=" z-index: 10 !important; background-color: #fff !important">
            <div class="sub-head">
                <div class="col-30 text-head">
                    @Html.ActionLink("TKQClock", "IndexBefore", "ClockStore")
                </div>
                <div class="col-30 btn-search-head">
                    <input type="text" class="searh-cl">
                    <button class="btn-head-search">
                        <i class="icon-head ti-search"></i>
                    </button>
                </div>
                <div class="col-30 btn-log">
                    <ul id="nav-log">
                        <li>
                            <a href="#">Tài khoản</a>
                            <ul class="subnav-log">
                                <li>@Html.ActionLink("Đăng nhập", "Dangnhap", "User")</li>
                                <li>@Html.ActionLink("Đăng ký", "Dangky", "User")</li>
                            </ul>
                        </li>
                        <li>@Html.Action("GiohangPartial", "Giohang") <i class="icon-shopping ti-shopping-cart"></i></li>
                    </ul>
                </div>
            </div>
            <ul id="nav">
                <li>
                    @Html.ActionLink("Trang chủ", "IndexBefore", "ClockStore")
                </li>
                <li>
                    @Html.ActionLink("Tin Tức", "Index", "TinTuc")
                </li>
                <li>
                    @Html.ActionLink("Sản phẩm", "Index", "ClockStore")
                </li>
                <li>
                    <a href="#">Hãng<i class="ti-angle-down"></i> </a>
                    <ul class="subnav">
                        @Html.Action("Hang", "ClockStore")
                    </ul>
                </li>
                <li>
                    <a href="#">Loại<i class="ti-angle-down"></i></a>
                    <ul class="subnav">
                        @Html.Action("Loai", "ClockStore")
                    </ul>
                </li>
                <li><a href="#map">Địa chỉ<i class="icon-cont ti-location-pin"></i></a></li>

                <li><a href="#contact">Hỗ trợ <i class="icon-help ti-headphone-alt"></i></a></li>
            </ul>

            <!-- begin search button -->
        </div>
    </div>
    <div>
        @RenderBody()
    </div>

    <div class="map-section">
        <iframe id="map" src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3918.4205948966046!2d106.78291401534769!3d10.855580060694717!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3175276e7ea103df%3A0xb6cf10bb7d719327!2zSHV0ZWNoIEtodSBFIC0gVHJ1bmcgVMOibSDEkMOgbyBU4bqhbyBOaMOibiBM4buxYyBDaOG6pXQgTMaw4bujbmcgQ2Fv!5e0!3m2!1svi!2s!4v1677309859870!5m2!1svi!2s" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
    </div>

    <div id="footer">
        <div class="social-list">
            <a href=""><i class="ti-facebook"></i></a>
            <a href=""><i class="ti-instagram"></i></a>
            <a href=""><i class="ti-youtube"></i></a>
            <a href=""><i class="ti-pinterest"></i></a>
            <a href=""><i class="ti-twitter"></i></a>
            <a href=""><i class="ti-linkedin"></i></a>
        </div>
        <p class="copyright">Copyright © 2023  TKQ Team. All rights reserved.</p>
    </div>
    </div>

</body>
</html>

TKQClock/Views/Shared/_LayoutUser.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <link rel="stylesheet" href="~/Content/ClockStoreCss/detail.css">
    <link href="~/Content/fondendfix.css" rel="stylesheet" />
    @*    <link rel="stylesheet" href="~/Content/ClockStoreCss/ThemeCart.css">*@
    @*<link rel="stylesheet" href="~/Content/ClockStoreCss/responsive.css">*@
    <link href="~/Content/ClockStoreCss/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/ClockStoreCss/shop-homepage.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/Content/themify-icons/themify-icons.css">
    <link rel="stylesheet" href="~/Content/ClockStoreCss/tintuc.css" />
    <link rel="shortcut icon" href="~/images/LOGO1.png" type="image/x-icon" />

</head>
<body>
    <style>
        center {
            display: none;
        }
    </style>
    <div class="main">
        <div id="header" style=" z-index: 10 !important; background-color: #fff !important">
            <div class="sub-head">
                <div class="col-30 text-head">
                    @Html.ActionLink("TKQClock", "IndexAfter", "User")
                </div>
                <div class="col-30 btn-search-head">
                    <input type="text" class="searh-cl">
                    <button class="btn-head-search">
                        <i class="icon-head ti-search"></i>
                    </button>
                </div>
                <div class="col-30 btn-log">
                    <ul id="nav-log">

                        <li>
                            <a href="#">Tài khoản<i class="ti-user"></i></a>
                            <ul class="subnav-log">
                                <li>@Html.ActionLink("Thông tin", "IfCustomer", "User")</li>
                                <li>@Html.ActionLink("Đăng xuất", "IndexBefore", "ClockStore")<i class="ti-shift-right"></i></li>
                            </ul>
                        </li>
                        <li>@Html.Action("GiohangPartial", "Giohang") <i class="icon-shopping ti-shopping-cart"></i></li>
                    </ul>
                </div>
            </div>
            <ul id="nav">
                <li>
                    @Html.ActionLink("Trang chủ", "IndexAfter", "User")
                </li>
                <li>
                    @Html.ActionLink("Sản phẩm", "Sanpham", "User")
                </li>
                <li>
                    @Html.ActionLink("Tin Tức", "News", "User")
                </li>
                <li>
                    <a href="#">Hãng<i class="ti-angle-down"></i> </a>
                    <ul class="subnav">
                        @Html.Action("Hang", "User")
                    </ul>
                </li>
                <li>
                    <a href="#">Loại<i class="ti-angle-down"></i></a>
                    <ul class="subnav">
                        @Html.Action("Loai", "User")
                    </ul>
                </li>
                <li><a href="#map">Địa chỉ<i class="icon-cont ti-location-pin"></i></a></li>

                <li><a href="#contact">Hỗ trợ <i class="icon-help ti-headphone-alt"></i></a></li>
            </ul>

            <!-- begin search button -->
        </div>
    </div>
    <div>
        @RenderBody()
    </div>

    <div class="map-section">
        <iframe id="map" src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3918.4205948966046!2d106.78291401534769!3d10.855580060694717!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3175276e7ea103df%3A0xb6cf10bb7d719327!2zSHV0ZWNoIEtodSBFIC0gVHJ1bmcgVMOibSDEkMOgbyBU4bqhbyBOaMOibiBM4buxYyBDaOG6pXQgTMaw4bujbmcgQ2Fv!5e0!3m2!1svi!2s!4v1677309859870!5m2!1svi!2s" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
    </div>

    <div id="footer">
        <div class="social-list">
            <a href=""><i class="ti-facebook"></i></a>
            <a href=""><i class="ti-instagram"></i></a>
            <a href=""><i class="ti-youtube"></i></a>
            <a href=""><i class="ti-pinterest"></i></a>
            <a href=""><i class="ti-twitter"></i></a>
            <a href=""><i class="ti-linkedin"></i></a>
        </div>
        <p class="copyright">Copyright © 2023  TKQ Team. All rights reserved.</p>
    </div>
    </div>

</body>
</html>

TKQClock/Views/Shared/_LayoutUserbefore.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <link rel="stylesheet" href="~/Content/ClockStoreCss/detail.css">
    <link href="~/Content/fondendfix.css" rel="stylesheet" />
    @*    <link rel="stylesheet" href="~/Content/ClockStoreCss/ThemeCart.css">*@
    @*@<link rel="stylesheet" href="~/Content/ClockStoreCss/responsive.css">*@
    <link href="~/Content/ClockStoreCss/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/ClockStoreCss/shop-homepage.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/Content/themify-icons/themify-icons.css">
    <link rel="stylesheet" href="~/Content/ClockStoreCss/tintuc.css" />
    <link rel="shortcut icon" href="~/images/LOGO1.png" type="image/x-icon" />

</head>
<body>
    <style>
        center {
            display: none;
        }
    </style>
    <div class="main">
        <div id="header" style=" z-index: 10 !important; background-color: #fff !important">
            <div class="sub-head">
                <div class="col-30 text-head">
                    @Html.ActionLink("TKQClock", "IndexBefore", "ClockStore")
                </div>
                <div class="col-30 btn-search-head">
                    <input type="text" class="searh-cl">
                    <button class="btn-head-search">
                        <i class="icon-head ti-search"></i>
                    </button>
                </div>
                <div class="col-30 btn-log">
                    <ul id="nav-log">
                        <li>
                            <a href="#">Tài khoản</a>
                            <ul class="subnav-log">
                                <li>@Html.ActionLink("Đăng nhập", "Dangnhap", "User")</li>
                                <li>@Html.ActionLink("Đăng ký", "Dangky", "User")</li>
                            </ul>
                        </li>
                        <li>@Html.Action("GiohangPartial", "Giohang") <i class="icon-shopping ti-shopping-cart"></i></li>
                    </ul>
                </div>
            </div>
            <ul id="nav">
                <li>
                    @Html.ActionLink("Trang chủ", "IndexBefore", "ClockStore")
                </li>
                <li>
                    @Html.ActionLink("Tin Tức", "Index", "TinTuc")
                </li>
                <li>
                    @Html.ActionLink("Sản phẩm", "Index", "ClockStore")
                </li>
                <li>
                    <a href="#">Hãng<i class="ti-angle-down"></i> </a>
                    <ul class="subnav">
                        @Html.Action("Hang", "ClockStore")
                    </ul>
                </li>
                <li>
                    <a href="#">Loại<i class="ti-angle-down"></i></a>
                    <ul class="subnav">
                        @Html.Action("Loai", "ClockStore")
                    </ul>
                </li>
                <li><a href="#map">Địa chỉ<i class="icon-cont ti-location-pin"></i></a></li>

                <li><a href="#contact">Hỗ trợ <i class="icon-help ti-headphone-alt"></i></a></li>
            </ul>

            <!-- begin search button -->
        </div>
    </div>
    <div>
        @RenderBody()
    </div>

    <div class="map-section">
        <iframe id="map" src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3918.4205948966046!2d106.78291401534769!3d10.855580060694717!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3175276e7ea103df%3A0xb6cf10bb7d719327!2zSHV0ZWNoIEtodSBFIC0gVHJ1bmcgVMOibSDEkMOgbyBU4bqhbyBOaMOibiBM4buxYyBDaOG6pXQgTMaw4bujbmcgQ2Fv!5e0!3m2!1svi!2s!4v1677309859870!5m2!1svi!2s" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
    </div>

    <div id="footer">
        <div class="social-list">
            <a href=""><i class="ti-facebook"></i></a>
            <a href=""><i class="ti-instagram"></i></a>
            <a href=""><i class="ti-youtube"></i></a>
            <a href=""><i class="ti-pinterest"></i></a>
            <a href=""><i class="ti-twitter"></i></a>
            <a href=""><i class="ti-linkedin"></i></a>
        </div>
        <p class="copyright">Copyright © 2023  TKQ Team. All rights reserved.</p>
    </div>
    </div>

</body>
</html>